---
# tasks file for kibana
- name: Create a directory /etc/kibana
  ansible.builtin.file:
    path: /etc/kibana
    state: directory

- name: Unarchive a file that needs to be downloaded (Kibana 3.x)
  ansible.builtin.unarchive:
    src: https://download.elastic.co/kibana/kibana/kibana-3.1.3.tar.gz
    dest: /etc/kibana/
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Replace line in /etc/kibana/config.js
  lineinfile: 
    path: /etc/kibana/config.js
    regexp: '{{ item.regexp }}' 
    line: '{{ item.line }}'
    backrefs: yes
  with_items: '{{ line_to_replace }}'
  notify:
    - Restart monit